package Pokemon.Effects.Abilities;

public enum Ability {
    RESISTANCE,
    WARRIOR_ZEAL,
    FEAR,
    BERSERK,
    INTIMIDATION,
    FULL_HEAL,
    SIMPLE_HEAL,
    KAMIKAZE,
    // ETHER_AFFINITY,
    // LEAD_AFFINITY,
    // USURPATION,
    // REGENERATION,
    // ZONE_HEAL,
    // POISON,
    // PERMANENT_HEAL,
    // PROTECT,
    // IMMUNITY,
    // DEJA_VU,
    // BLOCK,
    // NECROMANCY,
    // TERRITORY_EXPANSION,
    // MANIPULATION,
    // CONFUSION,
    // CHEAT,
}
