import Utils.HelperFunctions;

public class Display {
    // THIS CLASS IS RESPONSIBLE FOR DISPLAYING THE GAME, THE POKEMON, THE PLAYER, ETC.
    // IT WILL USE THE HELPER FUNCTIONS TO DISPLAY THE GAME IN A NICE WAY
    // IT WILL ALSO USE THE PLAYER AND POKEMON CLASSES TO DISPLAY THE PLAYER AND POKEMON
    // IT WILL USE THE GAME CLASS TO DISPLAY THE GAME STATUS
    
    public static void displayStartGame()
    {
        
    }
    
}
